language: python
python:
- "3.5"
- "3.6"
- "3.7"
dist: xenial
sudo: true
install:
- pip install marshmallow==2.20.1 requests-oauthlib requests
- pip install --pre pylint astroid
- pip install pytest
script:
- pylint toodledo
- pylint tests --disable=missing-docstring
- pytest -k test_get_account
- pytest -k test_get_tasks
